apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: chobot 
  janus-idp.io/tekton: chobot
  backstage.io/kubernetes-id: chobot
  backstage.io/kubernetes-namespace: ai-rhdh-app-development 
  app.kubernetes.io/part-of: chobot
resources: 
- application-dev.yaml