apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: chobot-gitops
  description: This is GitOps manifest for chobot   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: chobot
    janus-idp.io/tekton: chobot 
    backstage.io/kubernetes-id: chobot 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:chobot
