apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: chobot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chobot 
  name: chobot
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: chobot 
    weight: 100 
  wildcardPolicy: None
