apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: chobot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chobot 
  name: chobot
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: chobot 
